//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func RegisterDefaults(scheme *runtime.Scheme) error {
	return nil
}
