//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package resource

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Quantity) DeepCopyInto(out *Quantity) {
	*out = in.DeepCopy()
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantityValue) DeepCopyInto(out *QuantityValue) {
	*out = *in
	out.Quantity = in.Quantity.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantityValue.
func (in *QuantityValue) DeepCopy() *QuantityValue {
	if in == nil {
		return nil
	}
	out := new(QuantityValue)
	in.DeepCopyInto(out)
	return out
}
